<a href="https://colab.research.google.com/github/sriramrangu/AI_DOC-copy/blob/master/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import re
import nltk
import spacy
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [18]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [19]:
raw = "The Dogs are RUNNING quickly in the parks!!!"
print(f'Original : {raw}')

Original : The Dogs are RUNNING quickly in the parks!!!

In [20]:
#lowercasing
step_1 = raw.lower()
print(f"Lowercased : {step_1}\n")
#remove punctuation, !, . @,#
step_2 = re.sub(r"[^a-z\s]","",step_1)
print(f"Remove punctuation : {step_2}\n")

Lowercased : the dogs are running quickly in the parks!!!

Remove punctuation : the dogs are running quickly in the parks

In [21]:
stop_words = set(stopwords.words('english'))
print(len(stop_words))

198

In [22]:
step_3 = " ".join(w for w in step_2.split() if w not in stop_words)
print(f"Original : {raw}")
print(f"Stopwords removed : {step_3}")

Original : The Dogs are RUNNING quickly in the parks!!!
Stopwords removed : dogs running quickly parks

In [23]:
# Stemming
stemmer = PorterStemmer()
stemmed = " ".join(stemmer.stem(w) for w in step_3.split())
print(f"Stemmed : {stemmed}")

Stemmed : dog run quickli park

In [24]:
# Lemmatization
lemmatizer = WordNetLemmatizer()
lemma = " ".join(lemmatizer.lemmatize(w) for w in step_3.split())
print(f"After Lemmatization : {lemma}")

After Lemmatization : dog running quickly park

In [27]:
# spacy

nlp = spacy.load('en_core_web_sm')
doc = nlp("dog running quickly parks")
for token in doc:
  print(f"{token.text:12}")

dog
running
quickly
parks

In [ ]:
# TOkenization

In [28]:
import nltk
import spacy
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [30]:
text = "Sri Ram said that, He is studying NLP"
tokens = nltk.word_tokenize(text)
tokens

['Sri', 'Ram', 'said', 'that', ',', 'He', 'is', 'studying', 'NLP']

In [31]:
doc = nlp(text)
tokens_sp = [token.text for token in doc]
tokens_sp

['Sri', 'Ram', 'said', 'that', ',', 'He', 'is', 'studying', 'NLP']

In [34]:
# Sentence tokenazation
text = """"Telangana is a state in southern India on the Deccan Plateau bordering Maharashtra and Chhattisgarh to the north and Andhra Pradesh and Karnataka to the south. It is the eleventh largest and the twelfth most populated state of India. According to the Rigveda's Aitareya Brahmana,
  the region corresponding to Telangana has been inhabited by the Andhras since at least the 9th century BCE with the later Satavahana dynasty, who ruled over the entire Deccan Plateau, establishing trade relations as far as the Roman Empire.
  Subsequent major dynasties include the Vishnukundinas, Eastern Chalukyas, Kakatiyas, the Vijayanagara Empire, and Qutb Shahis,
   followed by the British Raj. Following the Independence of India,
   the Telugu speaking regions of India were gradually regrouped within the state of Andhra Pradesh
   but after decades of protests and agitations, the Telangana movement obtained its bifurcation with the creation, in 2014, of the state of Telangana corresponding to the Telugu speaking regions of the Princely State of Hyderabad."""
sentence_token = nltk.sent_tokenize(text)
for i, sent in enumerate(sentence_token):
  print(f"  Sentence {i+1} : {sent}")

  Sentence 1 : "Telangana is a state in southern India on the Deccan Plateau bordering Maharashtra and Chhattisgarh to the north and Andhra Pradesh and Karnataka to the south.
  Sentence 2 : It is the eleventh largest and the twelfth most populated state of India.
  Sentence 3 : According to the Rigveda's Aitareya Brahmana,
  the region corresponding to Telangana has been inhabited by the Andhras since at least the 9th century BCE with the later Satavahana dynasty, who ruled over the entire Deccan Plateau, establishing trade relations as far as the Roman Empire.
  Sentence 4 : Subsequent major dynasties include the Vishnukundinas, Eastern Chalukyas, Kakatiyas, the Vijayanagara Empire, and Qutb Shahis,
   followed by the British Raj.
  Sentence 5 : Following the Independence of India,
   the Telugu speaking regions of India were gradually regrouped within the state of Andhra Pradesh
   but after decades of protests and agitations, the Telangana movement obtained its bifurcation with the creation, in 2014, of the state of Telangana corresponding to the Telugu speaking regions of the Princely State of Hyderabad.

In [36]:
# Subword Tokenization (It is used in LLM's)
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
subword_tokens = tokenizer.tokenize("Unhappiness is problamatic")
print(subword_tokens)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

['un', '##ha', '##pp', '##iness', 'is', 'pro', '##bla', '##matic']

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [41]:
docs = ["the cat sat",
        'the dog sat',
        "the dog and the cat"]

bow_vector = CountVectorizer()
bow_matrix = bow_vector.fit_transform(docs)
bow_df = pd.DataFrame(bow_matrix.toarray(), columns= bow_vector.get_feature_names_out())
bow_df

   and  cat  dog  sat  the
0    0    1    0    1    1
1    0    0    1    1    1
2    1    1    1    0    2

In [44]:
docs = ["the cat sat",
        'the dog sat',
        "the dog and the cat"]
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(docs)
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns= tfidf_vec.get_feature_names_out())
tfidf_df

        and       cat       dog       sat       the
0  0.000000  0.619805  0.000000  0.619805  0.481334
1  0.000000  0.000000  0.619805  0.619805  0.481334
2  0.530587  0.403525  0.403525  0.000000  0.626747

In [ ]:
# TF-IDF >>> BOW (becz of the TF-IDF give more priority to TF)